### PR TITLE
Clean up telemetry and add option(s) to www interface (TTGO T-beam v.1.0 )

### PR DESCRIPTION
**Pull request by mattbk**
TTGO T-beam v.1.0 changes only.

The point of this is to clean up the telemetry information and give some control over it from the www interface. See also #59. Added numeric telemetry sequence rather than MIC by default.

- [x] telementry enable in www
- [x] telemetry interval in www
- [x] add www option for `MIC` telemetry rather than sequence
- [x] bug: sequence is not getting saved between reboots
- [x] notify when sending telemetry (blink and/or screen)
     - [x] screen
     - [x] flash LED
- [x] work with IS websites?
    - [x] aprs.fi (with T# sequence, not MIC)
    - [x] aprsdirect.com (with T# sequence, not MIC)
    - [x] do they show the same data?

Potential future work (not in this PR):
- choose which self telemetry values to send in www
- allow separate telemetry path in www

~~I will fill this in from my work at https://github.com/mattbk/TTGO-T-Beam-LoRa-APRS/pull/2, I didn't make the PR right in the first place.~~

### CODE REVIEW

**Comment by iu2frl** [comment]
I might just suggest to add few comments to get  better understanding of functions

**Comment by mattbk** [comment]
Nice intro to preference storage: https://randomnerdtutorials.com/esp32-save-data-permanently-preferences/

**Comment by mattbk** [comment]
aprs.fi
- B Volt
- B In
- B Out
- AC V
- AC C

aprsdirect.com
- B Volt
- B In
- B Out
- AC V
- AC C

Values match each other.

**Comment by mattbk** [comment]
Factory reset causing constant telemetry send, trying to fix.

**Comment by mattbk** [comment]
OK, now it's ready for someone to look at or test.

**Comment by SQ9MDD** [comment]
for TTGO 1.0 everything is ok but other versions do not compile. Will you check it?

**Comment by mattbk** [comment]
Yes, will try.

**Comment by SQ9MDD** [comment]
Oh... and Matt please add your call sign to the contributors at the bottom of the page. I would add myself but I don't know him

**Comment by SQ9MDD** [comment]
I'm thinking of a separate path for telemetry see: 
https://github.com/SQ9MDD/TTGO-T-Beam-LoRa-APRS/issues/77

**Pull request merged**
