### PR TITLE
Fix telemetry if statement

### PR DESCRIPTION
**Pull request by mattbk**
Fixes build problem (on my machine) introduced in #75.

image

### CODE REVIEW

**Comment by mattbk** [comment]
Feel free to rebase or squash commits on any of my PRs.

**Comment by iu2frl** [comment]
Does it only work with TBEAM 1.0?

**Comment by mattbk** [comment]
Currently, yes. That's how the original code was set up and I don't have another device to test with.

**Comment by iu2frl** [comment]
ok i'll try to port it to the 0.7

**Pull request merged**
